# Generated by Django 4.2.7 on 2023-11-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
