# Generated by Django 4.2.7 on 2024-04-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
