# Generated by Django 4.2.7 on 2023-11-21 14:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythoncourse',
            name='content',
            field=tinymce.models.HTMLField(default='content'),
        ),
    ]
