# Generated by Django 4.2.7 on 2024-04-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_delete_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course', models.ManyToManyField(to='tutorial.course')),
            ],
        ),
    ]
