# Generated by Django 4.2.7 on 2023-12-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_pythoncourse_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythoncourse',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
