# Generated by Django 4.2.7 on 2023-12-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_pythoncourse_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythoncourse',
            name='content',
        ),
    ]
