# Generated by Django 4.2.7 on 2024-04-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_tutoriallesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorialLesson',
        ),
    ]
