# Generated by Django 4.2.7 on 2024-04-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_delete_tutoriallesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='PythonCourse',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
