# Generated by Django 4.2.7 on 2024-04-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0009_lesson_maincourse_delete_course_lesson_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythoncourse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
