# Generated by Django 4.2.7 on 2024-05-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0013_alter_courseseries_tag_alter_lesson_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-pup_date']},
        ),
        migrations.AddField(
            model_name='courseseries',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_series_category', to='tutorial.category'),
        ),
    ]
