# Generated by Django 4.2.7 on 2024-05-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0014_alter_lesson_options_courseseries_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_in_sequence', to='tutorial.lesson'),
        ),
    ]
