# Generated by Django 4.2.7 on 2024-05-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0015_lesson_next_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='next_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_in_sequence', to='tutorial.lesson'),
        ),
    ]
