# Generated by Django 4.2.7 on 2024-05-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0016_alter_lesson_next_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pup_date']},
        ),
    ]
