# Generated by Django 4.2.7 on 2024-05-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0017_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseseries',
            name='featured_course',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseseries',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='featured_lesson',
            field=models.BooleanField(default=True),
        ),
    ]
