# Generated by Django 4.2.7 on 2024-06-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
