# Generated by Django 4.2.7 on 2024-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_remove_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='None', upload_to='media'),
        ),
    ]
