# Generated by Django 4.2.7 on 2024-06-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='tech.newscategory'),
        ),
    ]
