# Generated by Django 4.2.7 on 2024-10-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0010_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='external_link',
            field=models.CharField(blank=True, default='source link', max_length=500, null=True),
        ),
    ]
