# Generated by Django 4.2.7 on 2024-10-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0011_news_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, null=True),
        ),
    ]
