# Generated by Django 4.2.7 on 2024-10-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0012_newscategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
