# Generated by Django 4.2.7 on 2024-10-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0013_alter_newscategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
